<a href="https://colab.research.google.com/github/19PA1A04B7/pythonbasics/blob/master/Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
health=pd.read_csv("Andhra_Health_Data.csv")
health

         Sno  AGE     SEX  ... Mortality Y / N MORTALITY_DATE SRC_REGISTRATION
0          1   56  Female  ...              NO            NaN                D
1          2   37    Male  ...              NO            NaN                D
2          3   50    Male  ...              NO            NaN                D
3          4   45    Male  ...              NO            NaN                D
4          5   54    Male  ...              NO            NaN                D
...      ...  ...     ...  ...             ...            ...              ...
48507  48508   29    Male  ...              NO            NaN                D
48508  48509   53    Male  ...              NO            NaN                P
48509  48510   63    Male  ...              NO            NaN                D
48510  48511   52    Male  ...              NO            NaN                D
48511  48512   40  Female  ...             NaN            NaN              NaN

[48512 rows x 23 columns]